version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: vivaqui_postgres
    environment:
      POSTGRES_DB: VivaAqui
      POSTGRES_USER: app_admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2
    container_name: vivaqui_redis
    ports:
      - "6379:6379"

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: vivaqui_app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/VivaAqui
  #     SPRING_DATASOURCE_USERNAME: app_admin
  #     SPRING_DATASOURCE_PASSWORD: 123456
  #     SPRING_JPA_HIBERNATE_DDL_AUTO: update
  #     SPRING_REDIS_HOST: redis
  #     SPRING_REDIS_PORT: 6379

volumes:
  pgdata:
