version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: vivaqui_postgres
    environment:
      POSTGRES_DB: VivaAqui
      POSTGRES_USER: app_admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always


  redis:
    image: redis:6.2
    container_name: vivaqui_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
